import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "./components/header";
import MobileHeader from "./components/mobile-header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Aila Consulting",
	description: "Generated by create next app",
};

export default function RootLayout({
  	children,
}: Readonly<{
  	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{/* <Header />
				<MobileHeader /> */}
				{children}
			</body>
		</html>
	);
}
