import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Analytics } from "@vercel/analytics/react"
import { Toaster } from "@/components/ui/sonner";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Aila Consulting",
	description: "Generated by create next app",
	keywords: "visa, ikamet, residence permit, work permit, turkey, istanbul, aila, consulting",
};

export default function RootLayout({
  	children,
}: Readonly<{
  	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
				<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
				<link rel="shortcut icon" href="/favicon.ico" />
				<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
				<meta name="apple-mobile-web-app-title" content="Aila" />
				<link rel="manifest" href="/site.webmanifest" />
			</head>
			<body className={inter.className}>
				{children}
				<Toaster />
				<Analytics />
			</body>
		</html>
	);
}
